#!/bin/sh -eux

export PATH=/home/y/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
export MAVEN_OPTS=-Xmx384M

distflag=${1:-no}

rm -rf target

mvn --batch-mode -Dbuildtype=release package \
    javadoc:jar findbugs:findbugs checkstyle:checkstyle jxr:jxr \
    clover2:instrument clover2:clover \
    yinst:create

[ $distflag = dist ] &&  bb_dist_push src/ci/build.bim

exit 0
